Repository ethereum-optimism/optimistic-specs, pull requests merged in 2021-12, with the labels that each got.

#44 Add markdown linting and formatting with markdownlint
  .github/workflows/lint.yml
  .markdownlint.json
  package.json
  yarn.lock
Labels: process

#55 .gitignore and lint line-length fix
  .gitignore
  .markdownlint.json
Labels: presentation

#43 Rollup Node Spec
  glossary.md
  rollup-node.md
Labels: M-rollup-node

#54 Deposits spec
  deposits.md
  exec-engine.md
  glossary.md
  rollup-node.md
Labels: M-Layer-1-contracts

#58 rollup node: start on ref implementation (deposit-only rollup prototype)
  go.mod
  go.sum
  opnode/main.go
  opnode/node/api.go
  opnode/node/driver.go
  opnode/node/log.go
  opnode/node/node.go
  specs/exec-engine.md
  specs/glossary.md
  specs/rollup-node.md
Labels: M-rollup-node

#63 ci: golang linting and testing
  .github/workflows/go-ci.yml
  .github/workflows/lint.yml
  meta/linting.md
  opnode/main.go
  opnode/node/driver.go
  opnode/node/log.go
  opnode/node/node.go
Labels: process

#90 go mod: update ref optimistic geth, rebased onto latest merge-kintsugi branch
  go.mod
  go.sum
Labels: M-execution-engine, C-ref-impl
